# Generated by Django 4.0.4 on 2022-04-21 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authredis', '0002_alter_user_uid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='joinedAt',
        ),
        migrations.AlterField(
            model_name='user',
            name='uid',
            field=models.CharField(default='54350793-42ef-4dd0-bbc7-fb63c8cdfa3f', max_length=100, unique=True),
        ),
    ]
